# Generated by Django 3.1.2 on 2021-01-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_binatang', models.CharField(default='', max_length=250)),
                ('kategori', models.CharField(choices=[('darat', 'darat'), ('air', 'air')], max_length=50)),
            ],
        ),
    ]
